services:
  - type: web
    name: quiz-app-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ADMIN_SETUP_KEY
        sync: false
